name: publish_docs

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.adoc'
      - '.all-contributorsrc'
  create:
    tags:
      - '*'

jobs:
  publish_docs:
    if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
    runs-on: ubuntu-latest
    steps:
      - name: Prepare branch name
        run: >
          echo "refName=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Checkout relevant branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.refName }}
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: target/gh-pages
     
     
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          
      - name: Change Directory
        run: cd etc/antora
        
      - name: NPM Install
        run: npm install
        
      - name: Build Docs
        run: npm run build
        
      
      - name: Sync to Static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.NEO4J_DOCS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.NEO4J_DOCS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NEO4J_DOCS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.NEO4J_DOCS_S3_REGION }}
          # Upload from build/site
          SOURCE_DIR: etc/antora/build/site/migrations
          DEST_DIR: labs/neo4j-migrations/
